### ISSUE TITLE
Validate items not in metatable?

### ISSUE THREAD

**Issue by jacobdadams** [agrc/agol-validator#1]
The title, group, and folder checks rely on the information in the metatable. Right now the script iterates over every item in the organization's folders. Item's that don't have a corresponding itemid in the metatable are still checked against tags, downloads, and delete protection. 

Should these three checks still be done on non-metatable items, or should it only validate items found in the metatable?

**Comment by steveoh** [comment]
My first reaction is that it should only run on meta table items. 

If we do the entire org, we will dilute the results with one offs, testing data, and non SGID items. 

Am I understanding your question properly?

**Comment by jacobdadams** [comment]
Yeah, that was kind of my thought as well. 

Currently the shelved items are not in the metatable. While I wouldn't expect them to change enough to really warrant weekly validation, it doesn't cost a ton to validate them. Do we want to put them in the metatable, or create a separate table for shelved items?

**Comment by steveoh** [comment]
Yup, I forgot about static and shelved items. We should maintain a list of those as well and they should be validated for consistency in my opinion.

**Comment by jacobdadams** [comment]
Note to self: If we do create additional table(s) for shelved/static, edit code so that it won't require redundant passes over all the AGOL items for each table.

**Comment by steveoh** [comment]
As a result of some internal chatting, I think my opinion has changed to validate everything that is owned by UtahAGRC

**Comment by jacobdadams** [comment]
Note to self 2: Three options for shelved/static metatable:

1. Two new tables, one for shelved and one for static, same schema as metatable
2. One new table for both shelved and static, same schema as metatable plus additional field for static/shelved.
3. Add shelved/static data to metatable, add additional field for status (`db`/`static`/`shelved`, where `db` means its in SDE/openSGID—not using `SGID` because `static` data is still considered SGID data).

Impact on validator.py for each:

1. Rework logic to run checks multiple times in the main loop.
2. Same as 1.
3. Rework checks to evaluate status field for tags/folder/category.

**Comment by steveoh** [comment]
Do we need the new table(s) to store some ancillary data for the validation?

**Comment by jacobdadams** [comment]
At the dev team meeting we decided to store the shelved/static item info in a separate, AGOL-hosted metatable. This table has the same schema as `SGID.META.AGOLItems` with the addition of a 'CATEGORY' field to hold the `shelved`/`static` distinction.

All Hosted Feature Services in UtahAGRC's folders will be validated, but many checks rely on data from the metatables. If an item's ID is not in the metatables, it will only have its tags cleaned (proper case, redundant tags, 'Utah' tag added if not in title), delete protection enabled, and downloads enabled.
