### ISSUE TITLE
New Metadata Upload Logic 

### ISSUE THREAD

**Issue by jacobdadams** [agrc/agol-validator#18]
AGOL appears to be very picky about the xml you feed it as part of `item.metadata = some_metdata_xml` (or `item.update(metadata=path_to_xml`). The xml needs to be in the internal ArcGIS Metadata format (https://doc.arcgis.com/en/arcgis-online/manage-data/metadata.htm#ESRI_SECTION1_CE02409EE61D4A51A2BB943A2D8D982F, https://desktop.arcgis.com/en/arcmap/latest/manage-data/metadata/the-arcgis-metadata-format.htm). One possible way to make sure the xml is in this format is to export it using ArcGIS Desktop's `exact copy of.xslt` template (found in `<install dir>\Metadata\Stylesheets\gpTools`) and then update the AGOL metadata from this file.

Need to adjust the metadata fixer method to use this procedure. May also need to handle converting the SDE's metadata to the ArcGIS Metadata format (either in-place or make a copy.

**Comment by steveoh** [comment]
Does the exact copy of xslt exist in pro or only desktop?

**Comment by jacobdadams** [comment]
It looks like it only exists in desktop. I was just going to copy it to the repo- do you think that would have any license/copyright implications?

**Comment by steveoh** [comment]
I can't think of any license/copyright implications. The snapshot export of the xml is the bummer I would like to see removed.

**Comment by jacobdadams** [comment]
Agreed. My trial-and-error thus far indicates the formatting of the xml is important, and since they've provided a tool that seems to get the format right (at least so far), I didn't want to reinvent the wheel.
