### ISSUE TITLE
Empty tag

### ISSUE THREAD

**Issue by steveoh** [agrc/agol-validator#20]
![image](https://user-images.githubusercontent.com/325813/86976229-38e33d80-c137-11ea-90f3-1704fd25bcde.png)

I'm not sure what is causing this but I would assume the validator did this or if not, it should be able to fix this.

**Comment by jacobdadams** [comment]
You're right, it should catch that... what item is this?

**Comment by steveoh** [comment]
It's the new monuments and markers, https://www.arcgis.com/home/item.html?id=63de4118823e4e3eba943ca43caefc72

**Comment by jacobdadams** [comment]
The blank tag was pre-existing. It might have come in from the SDE metadata when the AGOL item was first published. The fix should catch any existing blank tags.
