### ISSUE TITLE
Tag Questions

### ISSUE THREAD

**Issue by jacobdadams** [agrc/agol-validator#4]
List of questions for the larger group about tags:
* Should all tags be proper cased? (ie, `Association of Governments`, `Shelved`, `Bioscience`, etc) (code is currently written to enforce this)
* Should shelved data be tagged with `SGID` (will also be tagged with `Shelved`, `Utah`, and `AGRC`)?

(More can be added later...)

**Comment by steveoh** [comment]
i prefer lowercase but i doubt my opinion will be popular.

**Comment by stdavis** [comment]
+1 for lowercase/kebab case for tags
`sgid`, `cadaster`, `two-words`

**Comment by jacobdadams** [comment]
I'm going to stick with proper case. The data team expressed a preference for proper case, and I feel like this is appropriate because the tags are primarily targeted to human beings, not computers. If these were purely for processing/automation, I'd agree with kebab case.
