### ISSUE TITLE
Add latest update date from stewardship doc

### ISSUE THREAD

**Issue by jacobdadams** [agrc/agol-validator#5]
Use the data from the stewardship doc to add a 'Last updated on <date>' line to the end or beginning of the AGOL description.

Read the stewardship doc in and add its info to the metatable_dict.

**Comment by steveoh** [comment]
I think it is a good idea to make this work symbiotically with the forklift pallet since it is common for people to forget to update the stewardship doc...

**Comment by jacobdadams** [comment]
Could you please explain what you mean by working symbiotically with forklift? I don't know enough about forklift to understand how/where it would set a last updated date somewhere outside of the stewardship doc.

**Comment by steveoh** [comment]
sure, the agol forklift pallet runs when the data actually changes which is a good hook to update the update date of the agol item's metadata. When someone forgets to edit the stewardship doc after an update, the forklift pallet would catch that and keep the date sync'd up with reality. 

On the other hand when someone remembers to update the doc this tool will update the metadata. I think the symbiosis would be along the lines of, if forklift updated the date and the stewardship doc had an older date, when your tool runs or vice versa don't change the date to be older than what is currently there?

**Comment by jacobdadams** [comment]
I'm going to leave this as a v2.0 enhancement. The data team is considering tracking the last updated date manually in the database's metadata description field.

**Comment by jacobdadams** [comment]
Last updated date will be included in the metadata's description field, which gets pulled in via the metadata checks.
