### ISSUE TITLE
Authoritative check/fix

### ISSUE THREAD

**Issue by jacobdadams** [agrc/agol-validator#8]
Once we get our authoritative datasets figured out, add a check/fix to set the authoritative flag. May require extending the metatables to add an authoritative flag.

**Comment by steveoh** [comment]
Is everything we serve not considered authoritative?

**Comment by jacobdadams** [comment]
I think theoretically yes (that's the point of the SGID, after all), but I wonder if some of the data we once got from other agencies, like bioscience or some of the DNR stuff, is not as authoritative as the fancy green check implies. 

If we determine that yes, everything in SGID is considered authoritative, then I can add that checker to every SGID item.

**Comment by steveoh** [comment]
My suggestion would be to add it and then peel it back if necessary.

**Comment by stdavis** [comment]
I think that the authoritative switch was going to be switched on once a human reviewed the layer. I don't think that anyone has taken that on. Or maybe with this project, we don't need to worry about a human taking a look at it?

**Comment by jacobdadams** [comment]
You're right, Scott, I forgot about that. I'll bring that up with Greg and Co.

**Comment by jacobdadams** [comment]
Implemented a check based on the AGOLItems table after talking it over with the data team. They will work on classifying everything in the table.
